# Generated by Django 2.1.7 on 2019-04-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
