# Generated by Django 2.1.7 on 2019-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0005_song_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
