# Generated by Django 2.1.7 on 2019-04-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs_app', '0006_auto_20190426_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='count',
            new_name='searches',
        ),
    ]
